-- 입양 시각 구하기(2)
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME_TABLE
LEFT JOIN ANIMAL_OUTS
ON HOUR(DATETIME) = TIME_TABLE.HOUR
group by HOUR
order by HOUR